### ISSUE TITLE
payload is not being retrieved at the Server.

### ISSUE THREAD

**Issue by salmandayal** [mpetazzoni/sse.js#12]
It's not being shown in req.body.payload.

![client](https://user-images.githubusercontent.com/17268239/88490028-e668a480-cfb1-11ea-9cfc-962bfd632b39.png)
![server](https://user-images.githubusercontent.com/17268239/88490030-e9639500-cfb1-11ea-837d-2e1012423e0f.png)

**Comment by mpetazzoni** [comment]
First things first: `payload` is the name of the argument to `sse.js` to tell it what payload to send with your request. That payload will directly become the request's body, so you should be looking for `req.body`, not `req.body.payload`, on the server side.

That being said, that still won't be enough to make it work talking to an Express app. By default `sse.js` will not set a content type on the POST request when sending your payload. This means it will simply be sent with `Content-Type: text/plain`. Neither the JSON or URLEncoded middlewares of Express will get you the request body in that situation.

As explained in the example at https://expressjs.com/en/api.html#req.body:

```js
app.use(express.json()) // for parsing application/json
app.use(express.urlencoded({ extended: true })) // for parsing application/x-www-form-urlencoded
```

I recommend you make `sse.js` set a header that's appropriate for your request, for example to send a JSON payload:

```js
new SSE(url, {
  payload: '"Hello!"', // A simple JSON string
  headers: {'Content-Type': 'application/json'}
});
```

And on the server side, just use the JSON middleware:

```js
app.use(express.json());
```

Now your `req.body` will contain the string `Hello!`.

**Comment by salmandayal** [comment]
Tried to send payload with Content-Type:application/json but getting an error on node server 
"SyntaxError: Unexpected token " in JSON at position 0". See attached images
![client](https://user-images.githubusercontent.com/17268239/88525497-18aaee00-d014-11ea-905d-9df5f5236dd1.png)
![server](https://user-images.githubusercontent.com/17268239/88525504-19dc1b00-d014-11ea-9df0-2497607a34d9.png)

**Comment by mpetazzoni** [comment]
Oh I guess just `"Hello!"` isn't valid JSON. Just pass in a valid JSON string as payload.
