### ISSUE TITLE
doesn't work with IE 11

### ISSUE THREAD

**Issue by ap-81** [mpetazzoni/sse.js#15]
I am using angular 9. I get a JS error (attached) on IE. My browserslist supports IE 9-11 and the target is set to es5 on tsconfig.json. I've included all the polyfills for IE on polyfill.ts.  

Does this library work on IE 11 ?

![image](https://user-images.githubusercontent.com/80429886/110863147-13ce3e00-8275-11eb-9a22-96f01cda5824.png)

![image](https://user-images.githubusercontent.com/80429886/110863523-a7a00a00-8275-11eb-9975-7f140f6b11fd.png)
![image](https://user-images.githubusercontent.com/80429886/110863533-acfd5480-8275-11eb-8cb5-63e1a6624afe.png)
![image](https://user-images.githubusercontent.com/80429886/110863548-b1297200-8275-11eb-839f-00846ef304ec.png)

**Comment by wmertens** [comment]
(note, I'm not mpetazzoni)

Can you figure out what code it fails on? I believe that if you have the debugger open you can have it show the line.

**Comment by ap-81** [comment]
I got this example from an article. stream() method throws the error.


![image](https://user-images.githubusercontent.com/80429886/110993078-af21ea80-832b-11eb-8d71-09b107bc5292.png)

**Comment by mpetazzoni** [comment]
`.stream()` isn't part of the original `EventSource` API. It's only in `sse.js` to make it easier to setup event listeners before starting the stream and avoid race conditions. But it's not required to use – in fact, it's only required if you explicitly set the `start: false` option in the SSE constructor.
