### ISSUE TITLE
Issue related to Firefox

### ISSUE THREAD

**Issue by jessequinn** [mpetazzoni/sse.js#18]
It appears Firefox keeps loading the page and never actually completely loads the page. For instance, we have dropdown side menus that would properly drop down when this script is disabled. When enabled, they do no drop down. Any ideas?

Happens only with Firefox, Chrome and Safari work.

**Comment by bennyboer** [comment]
I saw the same behavior, but it seems to be fixed if I postpone starting listening to the stream for a short while.

**Comment by mpetazzoni** [comment]
I can't reproduce this issue in Firefox. Feel free to re-open along with a code sample if you're still having this problem 🙏🏻
