### ISSUE TITLE
Improve XmlHttpRequest error handling and connection states

### ISSUE THREAD

**Issue by boamaod** [mpetazzoni/sse.js#23]
I rewrote and simplified XHR connection/event handling mechanism for my purposes as proposed in [TODO list](https://github.com/mpetazzoni/sse.js/blob/4085236f703efc9f3d90af9ca2a7bd6dbcbbd5af/README.md?plain=1#L130). It seems `error` and `abort` listeners are not needed at all, if `readystatechange` does all the work in the end, but I also directly followed EventSource event model, where `error` event announces changes to ready state. Since my aim was to enable reconnecting, this is also part of the code here:

* https://github.com/infoaed/sse.js/commit/9f1acec5e07691c12eb8845c3554eb1738153468

Please have a look and if this seems usable, I can create pull requests for some parts.

**Comment by mpetazzoni** [comment]
Recent work improves the ready state and error handling, and their related events fired from sse.js. I'll make a release with them soon. Thanks for your input and suggestions on this!
