### ISSUE TITLE
Im trying to use with react and ts, so i use npm i --save-dev @types/sse.js but it is giving me a error

### ISSUE THREAD

**Issue by PeterCastilloG** [mpetazzoni/sse.js#32]

**Comment by mpetazzoni** [comment]
@PeterCastilloG Can you provide more information about the error you're getting?

**Comment by quintesse** [comment]
Out of curiosity I tried this and it gives me:

```
→ npm i --save-dev @types/sse.js
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fsse.js - Not found
npm ERR! 404
npm ERR! 404  '@types/sse.js@*' is not in this registry.
```

**Comment by devbydaniel** [comment]
Same here. I am trying to use the library in a typescript project and for `import { SSE } from "sse.js` I see the following error:

```
Could not find a declaration file for module 'sse.js'. '/home/daniel/dev/llm-ui-web/node_modules/sse.js/lib/sse.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sse.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'sse.js';`ts(7016)
```

**Comment by dedalusMohantyMa** [comment]
I have tried to write some types yesterday for this project. I will open a PR, as soon as I know if they work (●'◡'●)

**Comment by dedalusMohantyMa** [comment]
Added PR https://github.com/mpetazzoni/sse.js/pull/42

**Comment by lujijiang** [comment]
It seems to have solved the problem and you should be able to merge and release it.

**Comment by dedalusMohantyMa** [comment]
@mpetazzoni thanks for the merge. I sadly was preoccupied with some work :-(

**Comment by mpetazzoni** [comment]
Thank _you_ @dedalusMohantyMa !
