### ISSUE TITLE
EventStream empty in Chrome Dev Tools?

### ISSUE THREAD

**Issue by quintesse** [mpetazzoni/sse.js#45]
Does anyone have any idea why Chrome isn't showing any events in the EventStream (Chrome DevTools/Network) when using POST with SSE? It might have to do with the non-standard use of POST of course, but it does actually show the EventStream tab, so it did correctly detect that we're dealing with a stream.

It's not important, because everything works just fine, but I was just curious if anyone was seeing the same thing and if there was some kind of fix.

**Comment by mpetazzoni** [comment]
It's unfortunately a bug in Chrome. See #39.

**Comment by quintesse** [comment]
Sorry, I did look into the closed issues to see if anybody else had asked this before, I promise. Obviously I didn't look hard enough :-)
