### ISSUE TITLE
this._checkStreamClosed Is Receiving A Null xhr in Firefox Only

### ISSUE THREAD

**Issue by ToucanBran** [mpetazzoni/sse.js#5]
Line 165 of sse.js throws an error in firefox only because this.xhr is null and it's trying to get the readyState. 

I think it's happening because line 192 sets this.xhr to null and that's triggering a readystatechange event which hits the checkStreamClosed callback. Why it's happening only in firefox, I have no clue.

**Comment by muety** [comment]
Same problem here.

**Comment by mpetazzoni** [comment]
@ToucanBran @muety Thanks for the report! It's unlikely that I would have time to look into that any time soon; would one of you have the time to propose a bug fix?

**Comment by ToucanBran** [comment]
@mpetazzoni sure, I'll put in a PR, seems like an easy null check

**Comment by muety** [comment]
@ToucanBran Very cool, thanks. And I don't think you need permission to open a PR, btw :wink:

**Comment by ToucanBran** [comment]
@mpetazzoni has this fixed been released yet?

**Comment by mpetazzoni** [comment]
It's been merged, but not released. Let me take care of that.

**Comment by mpetazzoni** [comment]
@ToucanBran Done, released and published v0.4.5 (https://www.npmjs.com/package/sse.js).
