### ISSUE TITLE
CORS error on post

### ISSUE THREAD

**Issue by IcelandicIcecream** [mpetazzoni/sse.js#53]
I keep getting a CORS error, it doesn't even send the request to my backend on a different server. (I already have these set in my backend:
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")

I'm guessing its a CORS error from SSE itself

**Comment by IcelandicIcecream** [comment]
Solved it by just removing "Content-Type": "application/json". As discussed here: https://github.com/mpetazzoni/sse.js/issues/52 but still unclear to why specifying the content type makes it have a CORS error.

**Comment by mpetazzoni** [comment]
@IcelandicIcecream This is indeed very curious, I still haven't found why this (and #52) are happening. Is an `OPTIONS` call being made? If so, does your backend answer it? If would be helpful if you can share an HTTP trace of the exchange (you can capture it with `ngrep -W byline '' 'tcp port 80'` (or whatever port you're sending requests to, obviously this is only helpful if not HTTPS).

**Comment by mpetazzoni** [comment]
@IcelandicIcecream If you add the following _request_ header via sse.js, does it help?

```js
new SSE(url, {
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Request-Headers': 'Content-Type'
  },
  payload: JSON.stringify({foo: 42})
);
```

**Comment by IcelandicIcecream** [comment]
> @IcelandicIcecream If you add the following _request_ header via sse.js, does it help?
> 
> ```js
> new SSE(url, {
>   headers: {
>     'Content-Type': 'application/json',
>     'Access-Control-Request-Headers': 'Content-Type'
>   },
>   payload: JSON.stringify({foo: 42})
> );
> ```

I get the same error. 
![image](https://github.com/mpetazzoni/sse.js/assets/36728442/83e43b3d-edee-432d-8826-22dcd433ddff)

Here's my HTTP trace:
```
OPTIONS /openai HTTP/1.1.
Host: localhost:8080.
Connection: keep-alive.
Accept: */*.
Access-Control-Request-Method: POST.
Access-Control-Request-Headers: content-type.
Origin: http://localhost:5173.
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.58.584.290 Safari/537.36.
Sec-Fetch-Mode: cors.
Sec-Fetch-Site: same-site.
Sec-Fetch-Dest: empty.
Referer: http://localhost:5173/.
Accept-Encoding: gzip, deflate, br.
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8.
.

##
HTTP/1.1 405 Method Not Allowed.
Allow: POST.
Content-Type: text/plain; charset=utf-8.
X-Content-Type-Options: nosniff.
Date: Tue, 27 Feb 2024 03:41:27 GMT.
Content-Length: 19.
.
Method Not Allowed
```

Sec-fetch-site is same site, where it shouldn't be for my use case. I think that's where the CORS error comes from. This is after me removing the headers, where it sends correctly:

```
HTTP/1.1 200 OK.
Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization.
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE.
Access-Control-Allow-Origin: *.
Cache-Control: no-cache.
Connection: keep-alive.
Content-Type: text/event-stream.
Date: Tue, 27 Feb 2024 03:43:29 GMT.
Transfer-Encoding: chunked.
```

**Comment by IcelandicIcecream** [comment]
Having it as text/plain works as well. I think it's most likely a browser issue (I'm using the sidekick browser) and how it handles sending application/json requests. I'll just be sending as plain text and then parsing the JSON manually.

**Comment by mpetazzoni** [comment]
Hmm, yeah, let me look into what those `Sec-*` headers are (since that's definitely not coming from sse.js), and if there's a way to control them.

**Comment by mpetazzoni** [comment]
@IcelandicIcecream In your case you might need to make your backend service's CORS middleware correctly handle [Fetch Metadata](https://web.dev/articles/fetch-metadata) policies to allow your particular situation. But either way, I don't think, this is anything the `sse.js` client library has much control over.
