### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [mpetazzoni/sse.js#54]
Hi,
Thank you for releasing SSE.js! It's licensed under the Apache license, which requires including a copy of it, but is it acceptable to  simply include the copyright notice included at the top of the file and a link to the GitHub repo?
Thanks!

**Comment by mpetazzoni** [comment]
Yes, that's fine. I've updated the Copyright header with license information as recommended by the Apache License 2.0, and published a new 2.3.0 version with it. So if you just include the `sse.js` file from that version or newer on your site, that's all you need. If you distribute it as part of a broader software package though, you need to include the full license as well.
