### ISSUE TITLE
Detect close

### ISSUE THREAD

**Issue by fakerybakery** [mpetazzoni/sse.js#55]
Hi
Is it possible to detect when the SSE is closed?
Thanks!

**Comment by mpetazzoni** [comment]
If the connection is closed by the server, you should receive an `abort` event, which you need to listen for:

```js
var source = new SSE(url, {start: false});
source.addEventListener('abort', function(e) { ... });
source.stream();
```

**Comment by fakerybakery** [comment]
Thanks!

**Comment by jayarjo** [comment]
Don't receive `abort` event. Ended up using custom `complete` event.
