### ISSUE TITLE
Missing properties in type SSEOptions

### ISSUE THREAD

**Issue by Holt59** [mpetazzoni/sse.js#56]
The `SSEOption` type declaration is missing some properties (e.g., `start`).

**Comment by Holt59** [comment]
@mpetazzoni Yes, it's simply missing from the latest release (2.3.0), I'll wait for the next one.

**Comment by Holt59** [comment]
@mpetazzoni Thanks, any idea when this will be published to npm?

**Comment by mpetazzoni** [comment]
@Holt59 Sorry! Done now.
