### ISSUE TITLE
How to determine when SSE connection was closed?

### ISSUE THREAD

**Issue by Blabter** [mpetazzoni/sse.js#63]
Let's say I have code
```ts
new SSE("/myurl").addEventListener("message", (customEvent) => {
    console.log("Received message");
});
```

Now after all messages was sent and server has closed connection I want to run `console.log("Closed")`. How I can do it?

And where I can find whole list of possible events SSE object can generate (except custom)? In Readme.md of this project I can see this list:
```
SSE, like EventSource, will emit the following events:

    open, when the first block of data is received from the event stream;
    error, if an error occurs while making the request;
    abort, as a response to the stream being explicitely aborted by the client;
    readystatechange, to notify of a change in the ready state of the event source.
```

But I assume it's not a complete list since I can't see `message` event here.

UPD:
I was able to determine when SSE connection was closed this way:
```ts
let sse = new SSE("/myurl");
sse.addEventListener("message", (customEvent) => {
    console.log("Received message");
});
sse.xhr.onload = () => console.log("Closed");
```

But I feel that accessing XMLHttpRequest is not "proper" way to do so. I would be glad if someone would say if there is more fluent way to add event listener for closing SSE connection.

**Comment by mpetazzoni** [comment]
You should be getting a `readystatechange` event with a `readystate` of `CLOSED`, as emmitted by https://github.com/mpetazzoni/sse.js/blob/main/lib/sse.js#L137-L140, called by https://github.com/mpetazzoni/sse.js/blob/main/lib/sse.js#L258-L260 when the XHR ready state changes and reaches the `DONE` state.
