### ISSUE TITLE
How to send multipart/form-date in SSE request with this library?

### ISSUE THREAD

**Issue by Blabter** [mpetazzoni/sse.js#67]
There is any handy way to do this?

**Comment by mpetazzoni** [comment]
@Blabter This library gives you full control over the HTTP request method, headers, and payload. You can use [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects) to make it easier to correctly encode the request body/payload. You should be able to do:

```js
var formData = new FormData();
formData.append("param1", "value1");
formData.append("param2", "value2");

var source = new SSE(url, {
  headers: {'Content-Type': 'multipart/form-data'},
  payload: formData
});
```
