### ISSUE TITLE
How to use this library without ECMAScript modules?

### ISSUE THREAD

**Issue by kkozlik** [mpetazzoni/sse.js#69]
I am using this library on some old version (pre 1.0.0). Now I am trying to update my project to latest versions, but I somehow cannot use sse.js without ECMAScript modules. Or if it is possible, please advice how.

When I try to load it the old way:
```html
<script type="text/javascript" src="/js/sse.js"></script>
```

The browser report syntax error: 
![image](https://github.com/mpetazzoni/sse.js/assets/1277199/c24c97f5-30bd-4d2e-af66-5d6af8fe2b1f)

If I try load it with this piece of code, it do not make it available in the rest of my javascript that do not use modules:
```html
<script type="module">
    import { SSE } from '/js/sse.js';
</script>
```

Maybe it would work if I change all the javascript into modules, but it looks to be a lot of changes in my case.

Probably you can generate two versions of the sse.js? One with the `export { SSE };` and one without it?

**Comment by mpetazzoni** [comment]
@kkozlik Hi,

Instead of using a `<script src="/js/sse.js"></script>` tag, which doesn't work because `sse.js` is a module, you need to load the module dynamically from your non-module context:

```html
<script type="text/javascript">
      (async () => {
        const { SSE } = await import('/js/sse.js');
        window.SSE = SSE;
      })();

      // You can use SSE from here, or any other <script> tag further down
    </script>
```
