### ISSUE TITLE
Stumbling block (limit of connections per brower)

### ISSUE THREAD

**Issue by mathiasms14** [mpetazzoni/sse.js#7]
I know that the native EventSource has a disadvantage, when opening various tabs as the limit is per browser and set to a very low number of connections (6). This lib also fix that issue?

**Comment by wmertens** [comment]
It can't fix this, this lib lives in a higher layer.

Http/2 solves this by multiplexing everything over a single connection. So if you can guarantee http/2, you don't have the problem.
