### ISSUE TITLE
Custom event listeners abruptly cease working

### ISSUE THREAD

**Issue by pengyuanyuan189** [mpetazzoni/sse.js#71]
In my project, I've encountered an issue with missing event handling for custom events emitted by my backend server. The frontend successfully sets up listeners for these events, and they works correctly most of the time. However, on occasion, it appears that the event listeners abruptly cease to function, particularly after a specific server event.

Here's an illustrative example of the server's response as seen in the Chrome console with debugging enabled:
 `{ "event": "start", "data": "start ..." },`
`...`
 `{ "event": "spin", "data": "70%" },`
` { "event": "step", "data": "finished transforming data format" },`
`{ "event": "spin", "data": "90%" },`
`{ "event": "step", "data": "save data to DB" },`
`{ "event": "output", "data": "{\"status\": \"SUCCESS\"}" },`
`{ "event": "end", "data": "" },`

In a typical scenario, after capturing the "spin" event with "90%" data, the frontend inexplicably fails to catch any subsequent events, despite their apparent transmission from the server.

I'm so confused that I can't get any idea to handle it: If an error occurs within the "spin" event handler, why would it impede the functioning of unrelated event listeners? Additionally, if the problem were rooted in network issues such as a lost connection, why are we still able to observe server-sent events (SSE) responses in the console?

The randomness of this issue makes it particularly challenging to debug, as it does not occur consistently. Consequently, I'm seeking assistance from the community to either resolve this perplexing problem or gain insight into its underlying cause. Any guidance or suggestions would be greatly appreciated.

**Comment by mpetazzoni** [comment]
Hi @pengyuanyuan189,

When you say "with debugging enabled", do you mean `sse.js`'s own debugging, passing `debug: true` in the options?
Would any of your event handlers registered on the SSE event source ever set `defaultPrevented` to true on the event?

If possible, would you be able to share your code here?

**Comment by pengyuanyuan189** [comment]
yes, I passed the `debug: true` in the options. But upon further inspection, I have discovered that the issue may well be rooted in a bug within my code. I'm gonna validate my hypothesis. Thank you for your response😊.
