### ISSUE TITLE
Can not get http status

### ISSUE THREAD

**Issue by sceneryfff** [mpetazzoni/sse.js#72]
The xhr.status I get is always 0. I cannot capture the 401 status code. I can already see 401 in network requests
<img width="486" alt="image" src="https://github.com/user-attachments/assets/2b766024-b93d-4704-8805-2b728a8a990e">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/f17c96b7-fb7f-4fb6-bdc5-b217d14db957">

**Comment by mpetazzoni** [comment]
@sceneryfff I pushed a fix for this, would you be able to try the latest version from the `main` branch?
