### ISSUE TITLE
Spec deviation for event values

### ISSUE THREAD

**Issue by sashirestela** [mpetazzoni/sse.js#73]
@mpetazzoni First that all, I want to say very thanks for your great library, I really like it.

I've detected a light spec deviation for event values, which is causing errors in my application when I'm using a backend library that is generating SSE with perfect alignment to the specs.

`sse.js` generates events in this format:
```
event: <type>\n
data: <data>\n
\n
```

but, according to the specs, it should be:
```
event:<type>\n
data:<data>\n
\n
```

The specs statements:

- [MDN Web Docs - Event stream format](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format)

![image](https://github.com/user-attachments/assets/56f4e9d0-6e11-490b-bffc-280775c4923c)

- [Html Spec - Server sent events - Interpreting an event stream](https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation)

![image](https://github.com/user-attachments/assets/3b530f6e-8af8-4b8c-b2e5-e423b723f4e7)

Could you provide a fix for this issue, please? In order to not impact current projects that are using `sse.js`, you could provide an optional configuration parameter to use a format aligned to the specs.

**Comment by mpetazzoni** [comment]
@sashirestela Thanks for raising this. Can you clarify what you mean by "sse.js generates events in this format"? This library receives events and allows you to handle them in your Javascript application, it does not itself produce the server-sent event stream.

You can also see that it correctly handles events coming in with or without a space after the colon, as described by the SSE spec: https://github.com/mpetazzoni/sse.js/blob/main/lib/sse.js#L218-L222

**Comment by sashirestela** [comment]
> @sashirestela Thanks for raising this. Can you clarify what you mean by "sse.js generates events in this format"? This library receives events and allows you to handle them in your Javascript application, it does not itself produce the server-sent event stream.

You're right, this library is not producing the events, but according to its documentation it is expecting them in that format with a space after the colon:

![image](https://github.com/user-attachments/assets/eceae74c-e7f4-48ae-ad38-da030cda917d)

What I see here is an interpretation issue:

The backend library that I've started to use ([Jooby](https://github.com/jooby-project/jooby/blob/3.x/jooby/src/main/java/io/jooby/ServerSentMessage.java)) it is generating SSE without any space-separator after the colon, but `sse.js` is removing any space after the colon (even if it is part of the data) and it is feeding the UI with different values than they were produced. In the following example you can see the problem.

When `Jooby` is producing data it could generate with some space at the beginning of the text (data is arriving from a LLM), but when `sse.js` is processing, it is removing unconditionally those front spaces:

| Jooby | sse.js |
|----------|---------|
| `'one'` | `'one'` |
| `' juicy '` | `'juicy '` |
| `'red'` | `'red'` |
| `' apple.'` | `'apple.'` |

I'm concatenating the data chunks to be shown in the UI, so the expected value is:

`one juicy red apple.`

but, due to the sse.js processing, currently I'm getting:

`onejuicy redapple.`

Can you see the issue here?

**Comment by mpetazzoni** [comment]
The documentation of sse.js is just an example, but I understand that it can cause confusion. I'll update it to be clearer and refer to the specification.

In this case, I do think the problem is in the Jooby library.

In your example, even with the server _not_ putting a space after the colon, the following event:

```
data: juicy
```

Should still give you `'juicy'` as the value, as the spec requires that if a space is present after the colon, it is removed from the value.

<img width="433" alt="image" src="https://github.com/user-attachments/assets/1f501e9e-5e19-4a8b-98c9-91b51c37bc98">

If your value (or any new line of the value) starts with a leading space, the server MUST write it with two spaces:

```
data:  juicy
```

I see you filed https://github.com/jooby-project/jooby/issues/3479, and hopefully the Jooby authors will address your issue.

**Comment by sashirestela** [comment]
@mpetazzoni Thanks for your comment in the Jooby repo.
