### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'status')  at SSE._onStreamFailure 

### ISSUE THREAD

**Issue by vojtabohm** [mpetazzoni/sse.js#74]
This error happens when the connection to a server is refused. For example if you don't have proper CSP or the server just refuses.

In the method:

```
this._onStreamFailure = function(e) {
    const event = new CustomEvent('error');
    event.responseCode = this.xhr.status;
    event.data = e.currentTarget.response;
    this.dispatchEvent(event);
    this._markClosed();
  }
```
 The `xhr` object seems to be null:
`at SSE._onStreamFailure (webpack-internal:///./node_modules/sse.js/lib/sse.js:155:35)`

**Comment by mpetazzoni** [comment]
Thanks for reporting! I'll take a look 👀

**Comment by vojtabohm** [comment]
Thank you for such a quick fix, man! 🫡

**Comment by vojtabohm** [comment]
Could I ask, how can I try-catch this in my codebase? I am trying to wrap the entire EventSource creation + callback setup in a try catch but when this library fails (reading .status on a null object) it still is thrown as a runtime exception and I cannot gracefully fail in the UI.

@mpetazzoni

**Comment by mpetazzoni** [comment]
You might be able to do that with https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event ?

**Comment by vojtabohm** [comment]
You're right, I am able to catch it with that :) Thanks!

**Comment by vojtabohm** [comment]
I'm returning to this issue. The `xhr` might be fixed but now, the .status is also `null`.

Starting a SSE connection while offline raises and exception:

```
Uncaught TypeError: Cannot read properties of null (reading 'status')
    at SSE._onStreamFailure (sse.js:155:35)
```

@mpetazzoni
