### ISSUE TITLE
ReadyState Enum

### ISSUE THREAD

**Issue by speak-jure** [mpetazzoni/sse.js#75]
Hello!

First of all, thank you for working on this project and sharing with the community! 🙏  I just transitioned over from the `@microsoft/fetch-event-source` package.

Given the following:
```Typescript
import { SSE, ReadyStateEvent } from 'sse.js';

const source = new SSE(url);

source.addEventListener('readystatechange', (e: ReadyStateEvent) => {
    if (e.readyState === SSE.CLOSED) {
        console.log('The connection has closed.');
    }
});
```
I've noticed that the console log never fired.

Digging into it a bit I've noticed that the `ReadyState` statuses (`INITIALIZING`, `CONNECTING`, `OPEN`, `CLOSED`) are initialized only as part of an instance of the SSE object. Meaning that if you access via `SSE.CLOSED`, `undefined` is returned, but if you access via `source.CLOSED`, the correct value of `2` is returned.

My question is, if it would make sense to have these ready states be static const values (exported outside of the `SSE` type) or maybe an enum instead?

**Comment by mpetazzoni** [comment]
Hi @speak-jure,

Thanks for bringing this up. You're absolutely right, I should do that, and it would help with making `sse.js` a drop-in replacement for `EventSource`, which does provide `EventSource.{CONNECTING,OPEN,CLOSED}` constants outside of an event source instance.

I'll work on that soon 👍🏻

**Comment by speak-jure** [comment]
@mpetazzoni Thank you, appreciate it!
