### ISSUE TITLE
With the error event handler, no way to see underlying error

### ISSUE THREAD

**Issue by aaronjwhiteside-appdirect** [mpetazzoni/sse.js#76]
```typescript
    eventSource.addEventListener("error", (e: SSEvent) => {
       console.log(`event: ${JSON.stringify(e)}`);
    });
```

When our endpoint returns Http 429, with a content body something like..

```json
{
    "message": "Usage rate limit exceeded for orgId=xxxxxxxx"
}
```

The SSEvent looks like 
```json
{
  "isTrusted": false,
  "source": {
    "INITIALIZING": -1,
    "CONNECTING": 0,
    "OPEN": 1,
    "CLOSED": 2,
    "url": "/api/v1/chats/xxxxx",
    "headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "payload": "{\"test\":\"Hello world\"}",
    "method": "POST",
    "withCredentials": true,
    "debug": false,
    "FIELD_SEPARATOR": ":",
    "listeners": {
      "tool.call": [
        null
      ],
      "message.delta": [
        null
      ],
      "error": [
        null
      ],
      "abort": [
        null
      ],
      "readystatechange": [
        null
      ]
    },
    "xhr": {},
    "readyState": 2,
    "progress": 0,
    "chunk": "",
    "lastEventId": ""
  }
}
```

There is no hint of the actual underlying error, it would be nice if this was returned in the `SSEvent` for the `error` handler

**Comment by mpetazzoni** [comment]
The `error` event will have the following fields:

* `responseCode`: the HTTP response code of the failed HTTP request
* `data`: the response _body_ of the failed HTTP request (that's what you're after!)
* `source`: the `SSE` instance itself

You should see those fields on the `error` event that gets fired:

<img width="735" alt="image" src="https://github.com/user-attachments/assets/1fd518c1-16d1-4641-9d8f-9e1fc26828b2">
