### ISSUE TITLE
HTTP status 201 closes the connection prematurely

### ISSUE THREAD

**Issue by dries-2002** [mpetazzoni/sse.js#79]
I recently integrated sse.js into my codebase. It works perfectly now. However, not without some debugging. 

In my case, the server responded with a HTTP status 201 (created), and the the library executed the `_onStreamFailure` routine, prematurely closing the connection. This might be by choice (I'm not an expert on HTTP status codes), but I didn't find any mention of it.  

What I propose is to either:
- update the docs to indicate the server should respond with a HTTP status 200
Or:
- extend the check to include the 2xx range

**Comment by mpetazzoni** [comment]
It's because of https://github.com/mpetazzoni/sse.js/blob/main/lib/sse.js#L159-L162, which could and should be relaxed indeed. I'll take a look!
