### ISSUE TITLE
CustomEvent is not defined

### ISSUE THREAD

**Issue by nilsroesel** [mpetazzoni/sse.js#8]
I think this needs the dom lib right?

**Comment by mpetazzoni** [comment]
No, although if you're using IE it's possible you're lacking support for the CustomEvent constructor:

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility

But really, you should not be using IE.

**Comment by nilsroesel** [comment]
To explain this: this issue is ment, when you want to use it serverside.
There the lib is not working at all. For solving this, used jsdom and injected the related dependencies into the module (i know its hakish as anything, but worked ;) )

**Comment by mpetazzoni** [comment]
Ah, yeah. Never intended for this to be used server-side, so never bothered to test that. You can also probably use the `custom-event-polyfill` instead, which might be more lightweight that the whole `jsdom`.

**Comment by nilsroesel** [comment]
Yep, i tried it, but there have been still some issues with that (maybe i did something wrong there). Anyways, the hackish approach works fine for me, so if anyone get into these troubles, he has a solution ;)

**Comment by horizon-plaza** [comment]
@nilsroesel : Hi, I am using this lib server side as well and see the same issue. Would you be kind enough to share how this is implemented. Code snippet much appreciated

**Comment by 0xTomDaniel** [comment]
@mpetazzoni Any plans to get this working server-side with Node? `custom-event-polyfill` isn't working.

**Comment by mpetazzoni** [comment]
@0xTomDaniel `CustomEvent` _should_ be available (as experimental) in more recent versions of Node, without the polyfill. Can you share what you've tried so far, and what errors / issues you're seeing? 🙏🏻
